shape: sequence_diagram
Комендант
Система
База данных
Студент
title: |md
  # Создание новости
| {near: top-center}
Регистрация: {
  Комендант -> Система: Регистрация в системе
  Система -> База данных: Создание пользователя
  База данных -> Система: Пользователь создан
  Система -> Комендант: Пользователь создан
  Студент -> Система: Регистрация в системе
  Система -> База данных: Создание пользователя
  База данных -> Система: Пользователь создан
  Система -> Студент: Пользователь создан
}
Вход в систему: {
  Комендант -> Система: Логин и пароль
  Система -> База данных: Хэш логин/пароль
  База данных -> Система: Access и refresh JWT-токены
  Система -> Комендант.cookie: JWT-токены
  Студент -> Система: Логин и пароль
  Система -> База данных: Хэш логин/пароль
  База данных -> Система: Access и refresh JWT-токены
  Система -> Студент.cookie: JWT-токены
}
Создание новости: {
  Комендант -> Система: Новость
  Система -> База данных: Новость, информация об авторе, время
  База данных -> Система: Обновленный список новостей
  Система -> Студент: Страница с новостями\n Уведомление
}