...@use_case
Отправка требования: {
  Комендант -> Система -> База данных: Требование для студента
  База данных -> Система: Новое требование для студента
  Система -> Студент: Уведомление о новом требовании
  Студент -> Система -> База данных: Ответ на требование
  База данных -> Система: Новый ответ от студента
  Система -> Комендант: Уведомление
}