direction: down
grid-rows: 3
vertical-gap: 200

title: |md
  # Use case
| {near: top-center}
Пользователи: {
  width: 1100
  horizontal-gap: 500
  grid-columns: 2
  Студент: {
    shape: person
  }
  Комендант: {
    shape: person
  }
}
Страница авторизации: {
  width: 1100
  direction: right
  grid-columns: 2
  horizontal-gap: 500
  Регистрация: {
    width: 300
  }
  Вход: {
    width: 300
  }
}
Главная страница: {
  grid-columns: 6
  width: 1100
  Отправка заявок
  Создание новостей
  Просмотр новостей
  Отправка требований
  Ответ на запрос студента
  Изменение данных пользователей
}
Пользователи.Студент -> Страница авторизации.Регистрация: Новые логин и пароль
Пользователи.Студент -> Страница авторизации.Вход: Логин и пароль
Пользователи.Комендант -> Страница авторизации.Регистрация: Новые логин и пароль
Пользователи.Комендант -> Страница авторизации.Вход: Логин и пароль
Страница авторизации.Регистрация -> Страница авторизации.Вход
Страница авторизации -> Главная страница: Доступ
Пользователи.Студент -> Главная страница.Отправка заявок
Пользователи.Студент -> Главная страница.Просмотр новостей
Пользователи.Комендант -> Главная страница.Создание новостей
Пользователи.Комендант -> Главная страница.Просмотр новостей
Пользователи.Комендант -> Главная страница.Отправка требований
Пользователи.Комендант -> Главная страница.Ответ на запрос студента
Пользователи.Комендант -> Главная страница.Изменение данных пользователей
Пользователи.Студент -> Главная страница.Изменение данных пользователей